spring.application.name=Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/conference
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=OIAJSNDFJklasnmdklaoAS923392NKSJANDJKlksanlda2989nkas
app.jwt.expiration-ms=86400000

app.admin.email=admin@conference.local
app.admin.password=Admin123!

app.manager.email=manager@conference.local
app.manager.password=Manager123!